---

name: Reusable Workflow to Make a Release

on:
  workflow_call:
    inputs:
      MAIN_FILE:
        required: true
        type: string

jobs:

  make-github-release:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Get current date (for tag)
        id: date
        run: echo "CURRENT=$(date +%F)" >> $GITHUB_OUTPUT
      - uses: actions/checkout@v4
      - uses: dawidd6/action-download-artifact@v3
        with:
          workflow: compile-lilypond.yml
      - name: Create CHANGELOG.latest file
        run: cp "$(ls -v changelog/* | tail -1)" CHANGELOG.latest
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.date.outputs.CURRENT }}
          body_path: CHANGELOG.latest
          files: |
            Lilypond Output/${{ inputs.MAIN_FILE }}.pdf
            Lilypond Output/${{ inputs.MAIN_FILE }}.midi
