---

name: Reusable Workflow to Push to release branch

on:
  workflow_call:
    inputs:
      MAIN_FILE:
        required: true
        type: string
      RELEASE_BRANCH:
        required: true
        type: string

jobs:

  create-branch:
    if: github.event_name == 'release' || github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    steps:
      - uses: peterjgrainger/action-create-branch@v2.4.0
        id: create-branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: ${{ inputs.RELEASE_BRANCH }}
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.RELEASE_BRANCH }}
      - name: Remove all files to avoid unwanted files being present
        run: find . -mindepth 1 -maxdepth 1 -not -path ./.git -exec rm -rvf {} +
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: ${{ inputs.RELEASE_BRANCH }}
          create_branch: true


  push-release:
    if: github.event_name == 'release' || github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    needs: create-branch
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.RELEASE_BRANCH }}
      - uses: dsaltares/fetch-gh-release-asset@master
        id: pdf
        with:
          version: latest
          file: ${{ inputs.MAIN_FILE }}.pdf
      - uses: dsaltares/fetch-gh-release-asset@master
        id: midi
        continue-on-error: true
        with:
          version: latest
          file: ${{ inputs.MAIN_FILE }}.midi
      - name: Prepare README file with shareable links
        run: echo "# Shareable jsDelivr link(s)" >> README.md
      - name: Add jsDelivr link for PDF fie
        run: |
          echo "## PDF" >> README.md
          perl -pe 's#(.*)/(.*)#- https://cdn.jsdelivr.net/gh/\1/\2\@${{ inputs.RELEASE_BRANCH }}/${{ inputs.MAIN_FILE }}.pdf#' <<< ${{ github.repository }} >> README.md
      - name: Add jsDelivr link for MIDI file
        if: ${{ steps.midi.outcome == 'success' }}
        run: |
          echo "## MIDI" >> README.md
          perl -pe 's#(.*)/(.*)#- https://cdn.jsdelivr.net/gh/\1/\2\@${{ inputs.RELEASE_BRANCH }}/${{ inputs.MAIN_FILE }}.midi#' <<< ${{ github.repository }} >> README.md
      - uses: stefanzweifel/git-auto-commit-action@v4
        if: always()
        with:
          branch: ${{ inputs.RELEASE_BRANCH }}
          create_branch: true

